In [2]:
import os
import numpy as np
import numpy_indexed as npi

In [124]:
path = "/home/liwei/Desktop/origami_data/state2.obj"
with open(path) as file:
    vertice = []
    face = []
    while 1:
        line = file.readline()
        if not line:
            break
        strs = line.split(" ")
        if strs[0] == "v":
            vertice.append([float(strs[1]), float(strs[2]), float(strs[3])])
        if strs[0] == "f":
            del strs[0]
            strs = np.array(strs)
            strs = strs.astype(int)
            strs = strs - 1
            face.append(strs)

vertice = np.array(vertice)
vertice = np.around(vertice, decimals=2)
face = np.array(face)

line = []
line_to_vertice = []
for i in range(len(face)):
    line_temp = []
    for j in range(1, len(face[i])-1):
        line_temp_vector1 = (vertice[face[i][j]] - vertice[face[i][j-1]]).tolist() #clockwise
        line_temp.append(line_temp_vector1)
        line_temp_vector2 = (vertice[face[i][j+1]] - vertice[face[i][j]]).tolist() #clockwise
        line_to_vertice.append([vertice[face[i][j]].tolist(), line_temp_vector1, line_temp_vector2])
    line_temp.append(line_temp_vector2) 
    line_temp_vector3 = (vertice[face[i][0]] - vertice[face[i][j+1]]).tolist()
    line_temp.append(line_temp_vector3)
    line_to_vertice.append([vertice[face[i][j+1]].tolist(), line_temp_vector2, line_temp_vector3])
    line_temp_vector4 = (vertice[face[i][1]] - vertice[face[i][0]]).tolist()
    line_to_vertice.append([vertice[face[i][0]].tolist(), line_temp_vector3, line_temp_vector4])

    line.append(line_temp) 

line = np.array(line)
line_to_vertice = np.array(line_to_vertice)

def findbyrow(mat,row):
    return np.where((mat == row).all(1))[0]

In [103]:
# # b = np.delete(line_to_vertice,[1,2],axis = 1)
# # b = b.reshape(len(b),3)

# # print b
# a = np.array([2,3,4])
# # print b[a]
# b = line_to_vertice[a]
# print b
# c = np.delete(b,0,axis = 1)
# c = c.reshape(len(c)*2,3)
# d = np.array(c)
# print c,d,type(d),d.shape

mat = [[200,0,0],[100,0,0],[0,100,0],[100,100,0]]

 [[[ 200.  200.    0.]
  [   0.  100.    0.]
  [-200.    0.    0.]]

 [[   0.  200.    0.]
  [-200.    0.    0.]
  [   0. -200.    0.]]

 [[   0.    0.    0.]
  [   0. -200.    0.]
  [ 100.    0.    0.]]]
[[   0.  100.    0.]
 [-200.    0.    0.]
 [-200.    0.    0.]
 [   0. -200.    0.]
 [   0. -200.    0.]
 [ 100.    0.    0.]] [[   0.  100.    0.]
 [-200.    0.    0.]
 [-200.    0.    0.]
 [   0. -200.    0.]
 [   0. -200.    0.]
 [ 100.    0.    0.]] <type 'numpy.ndarray'> (6, 3)


In [21]:
class State(object):
   
    def __init__(self,path):
        self.path = path
        self.vertice, self.line, self.face, self.line_to_vertice = self.data_process(path)
    
    def data_process(self, path):
        '''
        This function is used to process .obj file, will return arrays of vertice, line, and face.
        Vertice: shape(num_v,3), num_v is the number of all vertices. Type: array.
        Line: shape(num_f,num_v_in_f[i],3), num_f is the number of all faces, 
            num_v_in_f[i] is the number of vertices in the ith face. Type: array.
        Face: shape(num_f,num_v_in_f[i]), num_f is  the number of all faces,
            num_v_in_face[i] is the number of vertices in the ith face. Type: array.
        Line to vertice: shape(num_v,3,3), num_v is the number of vertices. Type: array.
            restore num_v vertices, and each vertice connects two lines.
            format:[[vertice1,connect line1,connect line2],[vertice2,connect line2,connect line3]...]
        '''
        with open(path) as file:
            vertice = []
            face = []
            while 1:
                line = file.readline()
                if not line:
                    break
                strs = line.split(" ")
                if strs[0] == "v":
                    vertice.append([float(strs[1]), float(strs[2]), float(strs[3])])
                if strs[0] == "f":
                    del strs[0]
                    strs = np.array(strs)
                    strs = strs.astype(int)
                    strs = strs - 1
                    face.append(strs)

        vertice = np.array(vertice)
        vertice = np.around(vertice, decimals=2)
        face = np.array(face)

        line = []
        line_to_vertice = []
        for i in range(len(face)):
            line_temp = []
            for j in range(1, len(face[i])-1):
                line_temp_vector1 = (vertice[face[i][j]] - vertice[face[i][j-1]]).tolist() #clockwise
                line_temp.append(line_temp_vector1)
                line_temp_vector2 = (vertice[face[i][j+1]] - vertice[face[i][j]]).tolist() #clockwise
                line_to_vertice.append([vertice[face[i][j]].tolist(), line_temp_vector1, line_temp_vector2])
            line_temp.append(line_temp_vector2) 
            line_temp_vector3 = (vertice[face[i][0]] - vertice[face[i][j+1]]).tolist()
            line_temp.append(line_temp_vector3)
            line_to_vertice.append([vertice[face[i][j+1]].tolist(), line_temp_vector2, line_temp_vector3])
            line_temp_vector4 = (vertice[face[i][1]] - vertice[face[i][0]]).tolist()
            line_to_vertice.append([vertice[face[i][0]].tolist(), line_temp_vector3, line_temp_vector4])

            line.append(line_temp)
        line = np.array(line)
        line_to_vertice = np.array(line_to_vertice)

        return vertice, line, face, line_to_vertice
    
    def update_path(self, new_path):
        self.path = new_path

In [149]:
class CompareState(object):
    def __init__(self,state1,state2):
        self.state1 = state1
        self.state2 = state2
        self.crease_line, self.crease_point, self.manipulatible_vertices = self.getCreaseLineAndManipulatibleVertice()
    def diff(self,arrayA,arrayB):       
        #difference
        diff_a = npi.difference(arrayA,arrayB)
        diff_b = npi.difference(arrayB,arrayA)
 
        return diff_a, diff_b

    def findbyrow(self,mat,row):
        return np.where((mat == row).all(1))[0]
    
    def getCreaseLineAndManipulatibleVertice(self):
        '''
        logic: 1)search starts from the bottom face
               2)compare the difference between face[i] of state1 and face[i] of state2
                 a)if no difference -> face[i] hasn't been folded during last folding action;
                 b)if 2 new points added in face[i] of state2 -> crease is the line connecting the 2 new points;
                 c)if no new points in face[i] of state2 -> compare the difference between line[i] of state1, 2
                     -> crease is the line that in line[i] of state2 but not in line[i] of state1;
                 d)if 1 new points added in face[i] of state2 -> normalize line[i] in state1 and state2
                     -> crease is the line that in line[i] of state2 but not in line[i] of state1;
               3)search the next face, go back to 2)
        '''
        num_f1 = len(self.state1.face)
        num_f2 = len(self.state2.face) #num_f1 <= num_f2
        
        crease_line = []
        v1 = self.state1.vertice
        v2 = self.state2.vertice    
        for i in range(num_f1):
            f1 = self.state1.face[i]
            f2 = self.state2.face[i]
            l1 = self.state1.line[i]
            l2 = self.state2.line[i]
            diff_1, diff_2 = self.diff(v1[f1], v2[f2])
    
            if len(diff_1) == 0 and len(diff_2) == 0:
                print "No new added crease line in face ", i
                continue
            elif len(diff_2) == 2:
                crease_line = diff_2[1] - diff_2[0]
                crease_point = diff_2[0]
                
            elif len(diff_2) == 1:
                line_temp1 = []
                line_temp2 = []
                for j in range(len(l1)):
                    temp = l1[j] / np.linalg.norm(l1[j])
                    line_temp1.append(temp)
                for j in range(len(l2[i])):
                    temp = l2[j] / np.linalg.norm(l2[j])
                    line_temp2.append(temp)
                _, crease_line = self.diff(line_temp1, line_temp2)
                crease_line = crease_line.flatten()
                index = self.findbyrow(line_temp2,crease_line)
                index == index[0]
                crease_point = v2[f2[index]].flatten()
                
            elif len(diff_2) == 0:
                _, crease_line = self.diff(l1, l2)
                crease_line = crease_line.flatten()
                index = self.findbyrow(l2,crease_line)
                index == index[0]
                crease_point = v2[f2[index]].flatten()

            manipulatible_vertices = diff_1
            
            if crease_line != []:
                break
                
        return crease_line, crease_point, manipulatible_vertices
    
    def getGraspTechnique(self):
        v1 = self.state1.vertice
        v2 = self.state2.vertice
        lv1 = self.state1.line_to_vertice
        lv2 = self.state2.line_to_vertice
        norm_crease = self.crease_line / np.linalg.norm(self.crease_line)
        print norm_crease

        v_temp = np.delete(self.manipulatible_vertices,-1,axis=1)
        
        lv1_temp = np.delete(lv1,[1,2],axis = 1)
        lv1_temp = lv1_temp.reshape(len(lv1_temp),3)
        lv1_temp = np.delete(lv1_temp,-1,axis = 1)
        

        for i in range(len(v_temp)):
            index = self.findbyrow(lv1_temp,v_temp[i])
            connect_lines = lv1[index]
            connect_lines = np.delete(connect_lines,0,axis = 1)
            connect_lines = connect_lines.reshape(len(connect_lines)*2,3)
            for j in range(len(connect_lines)):
                connect_lines[j] = connect_lines[j] / np.linalg.norm(connect_lines[j])
                if (connect_lines[j]==norm_crease).all() or (connect_lines[j]==-1*norm_crease).all() :
                    action = "scooping"
                    return action
                
        action = "flex flip"
        return action

        
    
        

In [150]:
path1 = "/home/liwei/Desktop/origami_data/state1.obj"
path2 = "/home/liwei/Desktop/origami_data/state2.obj"
state1 = State(path1)
state2 = State(path2)
compare = CompareState(state1,state2)

/home/liwei/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel_launcher.py:72: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


In [151]:
a,b,c = compare.getCreaseLineAndManipulatibleVertice()

x = compare.getGraspTechnique()
print x

[0.70710678 0.70710678 0.        ]
flex flip


/home/liwei/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel_launcher.py:72: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


In [67]:
a = [[0,0,1],[1,1,1]]
b = [[0,0,1],[1,2,1]]
x,y = diff(a,b)
print x,y

NameError: name 'diff' is not defined